import { Navbar } from "../components/shared/Navbar";
import { BlogNavbarWrapper } from "../components/blog/BlogNavbarWrapper";
import { css } from "../../styled-system/css";

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={css({
        px: "layout",
        pt: "layout",
        display: "flex",
        flexDirection: "column",
        h: "100dvh",
        maxH: "100dvh",
        overflow: "hidden",
        boxSizing: "border-box",
      })}
    >
      <BlogNavbarWrapper>
        <Navbar mode="sticky" />
      </BlogNavbarWrapper>
      <div
        className={css({
          flex: 1,
          minH: 0,
          display: "flex",
          flexDirection: "column",
        })}
      >
        {children}
      </div>
    </div>
  );
}
