import { Navbar } from "../components/shared/Navbar";

export const metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      <div>{children}</div>
    </>
  )
}