import { Navbar } from "../global_components/global_navbar"

export const metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <Navbar page="Blog"/>
      <div>{children}</div>
    </>
  )
}