/* eslint-disable @next/next/no-img-element */
import "./globals.css";
import { css } from "../styled-system/css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Analytics } from "@vercel/analytics/next";
config.autoAddCss = false;

export const metadata = {
  title: 'becker63',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={css({ color: "white" })}>
      <body>
        <img
          className={css({
            zIndex: "0",
            position: "fixed",
            inset: "0",
            margin: "auto",
            maxWidth: "70%",
            height: "auto",
            width: "auto",
            pointerEvents: "none",
          })}
          src="/img/backgroundImage.jpg"
          alt="blogcontent"
        />
        <div className={css({ position: "relative", zIndex: "1" })}>
          {children}
        </div>
        <Analytics />
      </body>
    </html>
  )
}
