/* eslint-disable @next/next/no-img-element */
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata = {
  title: 'becker63',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='text-white'>
      <body>
      <img
          className="z-[-1] fixed inset-0 mx-auto my-auto max-w-[70%] h-auto w-auto"
          src="/img/backgroundImage.jpg"
          alt="blogcontent"
        />
        {children}
      </body>
    </html>
  )
}
