import YAML from "yaml";
import { WorkflowFile } from "./definitions";

const header = [
  "# Generated from automation/repo-insight/workflows/definitions.ts",
  "# Do not edit this file directly. Run pnpm automation:generate-workflows.",
  "",
].join("\n");

export const renderWorkflow = (workflow: WorkflowFile) =>
  header +
  YAML.stringify(workflow.workflow, {
    lineWidth: 0,
    nullStr: "",
    // GitHub cron expressions contain `*`; keep only that fragile scalar quoted.
  })
    .replace("cron: 17 * * * *", 'cron: "17 * * * *"')
    .replace("cron: 47 13 * * 0", 'cron: "47 13 * * 0"');
