import YAML from "yaml";
import { WorkflowFile } from "./definitions";

const header = [
  "# Generated from automation/repo-insight/workflows/definitions.ts",
  "# Do not edit this file directly. Run pnpm automation:generate-workflows.",
  "",
].join("\n");

const quoteCronScalars = (yaml: string) =>
  yaml.replace(/^(\s*)(-\s+)?cron:\s*(.+)$/gm, (_line, indent, listMarker, value) => {
    const trimmed = String(value).trim();
    const marker = listMarker ?? "";
    if (trimmed.startsWith('"') && trimmed.endsWith('"')) return `${indent}${marker}cron: ${trimmed}`;
    const escaped = trimmed.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `${indent}${marker}cron: "${escaped}"`;
  });

export const renderWorkflow = (workflow: WorkflowFile) =>
  header + quoteCronScalars(YAML.stringify(workflow.workflow, { lineWidth: 0, nullStr: "" }));
